
namespace b201210009
{
    partial class UsFatura
    {
        /// <summary> 
        ///Gerekli tasarımcı değişkeni.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        ///Kullanılan tüm kaynakları temizleyin.
        /// </summary>
        ///<param name="disposing">yönetilen kaynaklar dispose edilmeliyse doğru; aksi halde yanlış.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Bileşen Tasarımcısı üretimi kod

        /// <summary> 
        /// Tasarımcı desteği için gerekli metot - bu metodun 
        ///içeriğini kod düzenleyici ile değiştirmeyin.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(UsFatura));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuElipse2 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuButton22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.ara = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.sil = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.duzenle = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.bunifuDataGridView1 = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.ekle = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 25;
            this.bunifuElipse1.TargetControl = this;
            // 
            // bunifuElipse2
            // 
            this.bunifuElipse2.ElipseRadius = 25;
            this.bunifuElipse2.TargetControl = this;
            // 
            // bunifuButton22
            // 
            this.bunifuButton22.AllowAnimations = true;
            this.bunifuButton22.AllowMouseEffects = true;
            this.bunifuButton22.AllowToggling = false;
            this.bunifuButton22.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.bunifuButton22.AnimationSpeed = 200;
            this.bunifuButton22.AutoGenerateColors = false;
            this.bunifuButton22.AutoRoundBorders = false;
            this.bunifuButton22.AutoSizeLeftIcon = true;
            this.bunifuButton22.AutoSizeRightIcon = true;
            this.bunifuButton22.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton22.BackColor1 = System.Drawing.Color.White;
            this.bunifuButton22.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton22.BackgroundImage")));
            this.bunifuButton22.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.ButtonText = "Satış Faturaları";
            this.bunifuButton22.ButtonTextMarginLeft = 0;
            this.bunifuButton22.ColorContrastOnClick = 45;
            this.bunifuButton22.ColorContrastOnHover = 45;
            this.bunifuButton22.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton22.CustomizableEdges = borderEdges1;
            this.bunifuButton22.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton22.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton22.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton22.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton22.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton22.Font = new System.Drawing.Font("Bahnschrift SemiBold SemiConden", 11.25F, System.Drawing.FontStyle.Bold);
            this.bunifuButton22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.bunifuButton22.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton22.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton22.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton22.IconMarginLeft = 11;
            this.bunifuButton22.IconPadding = 10;
            this.bunifuButton22.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton22.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton22.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton22.IconSize = 25;
            this.bunifuButton22.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.bunifuButton22.IdleBorderRadius = 25;
            this.bunifuButton22.IdleBorderThickness = 2;
            this.bunifuButton22.IdleFillColor = System.Drawing.Color.White;
            this.bunifuButton22.IdleIconLeftImage = null;
            this.bunifuButton22.IdleIconRightImage = null;
            this.bunifuButton22.IndicateFocus = false;
            this.bunifuButton22.Location = new System.Drawing.Point(241, 28);
            this.bunifuButton22.Name = "bunifuButton22";
            this.bunifuButton22.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton22.OnDisabledState.BorderRadius = 25;
            this.bunifuButton22.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnDisabledState.BorderThickness = 2;
            this.bunifuButton22.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton22.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton22.OnDisabledState.IconLeftImage = null;
            this.bunifuButton22.OnDisabledState.IconRightImage = null;
            this.bunifuButton22.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.bunifuButton22.onHoverState.BorderRadius = 25;
            this.bunifuButton22.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.onHoverState.BorderThickness = 2;
            this.bunifuButton22.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.bunifuButton22.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.onHoverState.IconLeftImage = null;
            this.bunifuButton22.onHoverState.IconRightImage = null;
            this.bunifuButton22.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.bunifuButton22.OnIdleState.BorderRadius = 25;
            this.bunifuButton22.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnIdleState.BorderThickness = 2;
            this.bunifuButton22.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bunifuButton22.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.bunifuButton22.OnIdleState.IconLeftImage = null;
            this.bunifuButton22.OnIdleState.IconRightImage = null;
            this.bunifuButton22.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton22.OnPressedState.BorderRadius = 25;
            this.bunifuButton22.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton22.OnPressedState.BorderThickness = 2;
            this.bunifuButton22.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton22.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton22.OnPressedState.IconLeftImage = null;
            this.bunifuButton22.OnPressedState.IconRightImage = null;
            this.bunifuButton22.Size = new System.Drawing.Size(215, 35);
            this.bunifuButton22.TabIndex = 18;
            this.bunifuButton22.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton22.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton22.TextMarginLeft = 0;
            this.bunifuButton22.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton22.UseDefaultRadiusAndThickness = true;
            this.bunifuButton22.Click += new System.EventHandler(this.bunifuButton22_Click);
            // 
            // bunifuButton21
            // 
            this.bunifuButton21.AllowAnimations = true;
            this.bunifuButton21.AllowMouseEffects = true;
            this.bunifuButton21.AllowToggling = false;
            this.bunifuButton21.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.bunifuButton21.AnimationSpeed = 200;
            this.bunifuButton21.AutoGenerateColors = false;
            this.bunifuButton21.AutoRoundBorders = false;
            this.bunifuButton21.AutoSizeLeftIcon = true;
            this.bunifuButton21.AutoSizeRightIcon = true;
            this.bunifuButton21.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.BackColor1 = System.Drawing.Color.White;
            this.bunifuButton21.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.BackgroundImage")));
            this.bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.ButtonText = "Satın Alma Faturaları";
            this.bunifuButton21.ButtonTextMarginLeft = 0;
            this.bunifuButton21.ColorContrastOnClick = 45;
            this.bunifuButton21.ColorContrastOnHover = 45;
            this.bunifuButton21.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton21.CustomizableEdges = borderEdges2;
            this.bunifuButton21.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton21.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton21.Font = new System.Drawing.Font("Bahnschrift SemiBold SemiConden", 11.25F, System.Drawing.FontStyle.Bold);
            this.bunifuButton21.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.bunifuButton21.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton21.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton21.IconMarginLeft = 11;
            this.bunifuButton21.IconPadding = 10;
            this.bunifuButton21.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton21.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton21.IconSize = 25;
            this.bunifuButton21.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.bunifuButton21.IdleBorderRadius = 25;
            this.bunifuButton21.IdleBorderThickness = 2;
            this.bunifuButton21.IdleFillColor = System.Drawing.Color.White;
            this.bunifuButton21.IdleIconLeftImage = null;
            this.bunifuButton21.IdleIconRightImage = null;
            this.bunifuButton21.IndicateFocus = false;
            this.bunifuButton21.Location = new System.Drawing.Point(20, 28);
            this.bunifuButton21.Name = "bunifuButton21";
            this.bunifuButton21.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.OnDisabledState.BorderRadius = 25;
            this.bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnDisabledState.BorderThickness = 2;
            this.bunifuButton21.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.OnDisabledState.IconLeftImage = null;
            this.bunifuButton21.OnDisabledState.IconRightImage = null;
            this.bunifuButton21.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.bunifuButton21.onHoverState.BorderRadius = 25;
            this.bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.onHoverState.BorderThickness = 2;
            this.bunifuButton21.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.bunifuButton21.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.onHoverState.IconLeftImage = null;
            this.bunifuButton21.onHoverState.IconRightImage = null;
            this.bunifuButton21.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.bunifuButton21.OnIdleState.BorderRadius = 25;
            this.bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnIdleState.BorderThickness = 2;
            this.bunifuButton21.OnIdleState.FillColor = System.Drawing.Color.White;
            this.bunifuButton21.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.bunifuButton21.OnIdleState.IconLeftImage = null;
            this.bunifuButton21.OnIdleState.IconRightImage = null;
            this.bunifuButton21.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.BorderRadius = 25;
            this.bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnPressedState.BorderThickness = 2;
            this.bunifuButton21.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnPressedState.IconLeftImage = null;
            this.bunifuButton21.OnPressedState.IconRightImage = null;
            this.bunifuButton21.Size = new System.Drawing.Size(215, 35);
            this.bunifuButton21.TabIndex = 19;
            this.bunifuButton21.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton21.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton21.TextMarginLeft = 0;
            this.bunifuButton21.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton21.UseDefaultRadiusAndThickness = true;
            this.bunifuButton21.Click += new System.EventHandler(this.bunifuButton21_Click);
            // 
            // ara
            // 
            this.ara.AllowAnimations = true;
            this.ara.AllowMouseEffects = true;
            this.ara.AllowToggling = false;
            this.ara.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.ara.AnimationSpeed = 200;
            this.ara.AutoGenerateColors = false;
            this.ara.AutoRoundBorders = false;
            this.ara.AutoSizeLeftIcon = true;
            this.ara.AutoSizeRightIcon = true;
            this.ara.BackColor = System.Drawing.Color.Transparent;
            this.ara.BackColor1 = System.Drawing.Color.White;
            this.ara.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ara.BackgroundImage")));
            this.ara.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.ara.ButtonText = "";
            this.ara.ButtonTextMarginLeft = 0;
            this.ara.ColorContrastOnClick = 45;
            this.ara.ColorContrastOnHover = 45;
            this.ara.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.ara.CustomizableEdges = borderEdges3;
            this.ara.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ara.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ara.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ara.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ara.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.ara.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ara.ForeColor = System.Drawing.Color.White;
            this.ara.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ara.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ara.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.ara.IconMarginLeft = 11;
            this.ara.IconPadding = 5;
            this.ara.IconRightAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ara.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ara.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ara.IconSize = 25;
            this.ara.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.ara.IdleBorderRadius = 25;
            this.ara.IdleBorderThickness = 2;
            this.ara.IdleFillColor = System.Drawing.Color.White;
            this.ara.IdleIconLeftImage = global::b201210009.Properties.Resources.ara1;
            this.ara.IdleIconRightImage = null;
            this.ara.IndicateFocus = false;
            this.ara.Location = new System.Drawing.Point(699, 28);
            this.ara.Margin = new System.Windows.Forms.Padding(2);
            this.ara.Name = "ara";
            this.ara.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ara.OnDisabledState.BorderRadius = 25;
            this.ara.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.ara.OnDisabledState.BorderThickness = 2;
            this.ara.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ara.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ara.OnDisabledState.IconLeftImage = null;
            this.ara.OnDisabledState.IconRightImage = null;
            this.ara.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.ara.onHoverState.BorderRadius = 25;
            this.ara.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.ara.onHoverState.BorderThickness = 2;
            this.ara.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.ara.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ara.onHoverState.IconLeftImage = global::b201210009.Properties.Resources.araBeyaz;
            this.ara.onHoverState.IconRightImage = null;
            this.ara.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.ara.OnIdleState.BorderRadius = 25;
            this.ara.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.ara.OnIdleState.BorderThickness = 2;
            this.ara.OnIdleState.FillColor = System.Drawing.Color.White;
            this.ara.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.ara.OnIdleState.IconLeftImage = global::b201210009.Properties.Resources.ara1;
            this.ara.OnIdleState.IconRightImage = null;
            this.ara.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ara.OnPressedState.BorderRadius = 25;
            this.ara.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.ara.OnPressedState.BorderThickness = 2;
            this.ara.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ara.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ara.OnPressedState.IconLeftImage = global::b201210009.Properties.Resources.araBeyaz;
            this.ara.OnPressedState.IconRightImage = null;
            this.ara.Size = new System.Drawing.Size(35, 35);
            this.ara.TabIndex = 14;
            this.ara.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ara.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ara.TextMarginLeft = 0;
            this.ara.TextPadding = new System.Windows.Forms.Padding(0);
            this.ara.UseDefaultRadiusAndThickness = true;
            this.ara.Click += new System.EventHandler(this.ara_Click);
            // 
            // sil
            // 
            this.sil.AllowAnimations = true;
            this.sil.AllowMouseEffects = true;
            this.sil.AllowToggling = false;
            this.sil.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.sil.AnimationSpeed = 200;
            this.sil.AutoGenerateColors = false;
            this.sil.AutoRoundBorders = false;
            this.sil.AutoSizeLeftIcon = true;
            this.sil.AutoSizeRightIcon = true;
            this.sil.BackColor = System.Drawing.Color.Transparent;
            this.sil.BackColor1 = System.Drawing.Color.White;
            this.sil.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("sil.BackgroundImage")));
            this.sil.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.sil.ButtonText = "";
            this.sil.ButtonTextMarginLeft = 0;
            this.sil.ColorContrastOnClick = 45;
            this.sil.ColorContrastOnHover = 45;
            this.sil.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.sil.CustomizableEdges = borderEdges4;
            this.sil.DialogResult = System.Windows.Forms.DialogResult.None;
            this.sil.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.sil.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.sil.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.sil.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.sil.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.sil.ForeColor = System.Drawing.Color.White;
            this.sil.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.sil.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.sil.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.sil.IconMarginLeft = 11;
            this.sil.IconPadding = 5;
            this.sil.IconRightAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.sil.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.sil.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.sil.IconSize = 25;
            this.sil.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.sil.IdleBorderRadius = 25;
            this.sil.IdleBorderThickness = 2;
            this.sil.IdleFillColor = System.Drawing.Color.White;
            this.sil.IdleIconLeftImage = global::b201210009.Properties.Resources.sil1;
            this.sil.IdleIconRightImage = null;
            this.sil.IndicateFocus = false;
            this.sil.Location = new System.Drawing.Point(816, 28);
            this.sil.Margin = new System.Windows.Forms.Padding(2, 30, 30, 30);
            this.sil.Name = "sil";
            this.sil.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.sil.OnDisabledState.BorderRadius = 25;
            this.sil.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.sil.OnDisabledState.BorderThickness = 2;
            this.sil.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.sil.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.sil.OnDisabledState.IconLeftImage = null;
            this.sil.OnDisabledState.IconRightImage = null;
            this.sil.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.sil.onHoverState.BorderRadius = 25;
            this.sil.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.sil.onHoverState.BorderThickness = 2;
            this.sil.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.sil.onHoverState.ForeColor = System.Drawing.Color.White;
            this.sil.onHoverState.IconLeftImage = global::b201210009.Properties.Resources.silBeyaz;
            this.sil.onHoverState.IconRightImage = null;
            this.sil.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.sil.OnIdleState.BorderRadius = 25;
            this.sil.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.sil.OnIdleState.BorderThickness = 2;
            this.sil.OnIdleState.FillColor = System.Drawing.Color.White;
            this.sil.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.sil.OnIdleState.IconLeftImage = global::b201210009.Properties.Resources.sil1;
            this.sil.OnIdleState.IconRightImage = null;
            this.sil.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.sil.OnPressedState.BorderRadius = 25;
            this.sil.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.sil.OnPressedState.BorderThickness = 2;
            this.sil.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.sil.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.sil.OnPressedState.IconLeftImage = global::b201210009.Properties.Resources.silBeyaz;
            this.sil.OnPressedState.IconRightImage = null;
            this.sil.Size = new System.Drawing.Size(35, 35);
            this.sil.TabIndex = 15;
            this.sil.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.sil.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.sil.TextMarginLeft = 0;
            this.sil.TextPadding = new System.Windows.Forms.Padding(0);
            this.sil.UseDefaultRadiusAndThickness = true;
            // 
            // duzenle
            // 
            this.duzenle.AllowAnimations = true;
            this.duzenle.AllowMouseEffects = true;
            this.duzenle.AllowToggling = false;
            this.duzenle.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.duzenle.AnimationSpeed = 200;
            this.duzenle.AutoGenerateColors = false;
            this.duzenle.AutoRoundBorders = false;
            this.duzenle.AutoSizeLeftIcon = true;
            this.duzenle.AutoSizeRightIcon = true;
            this.duzenle.BackColor = System.Drawing.Color.Transparent;
            this.duzenle.BackColor1 = System.Drawing.Color.White;
            this.duzenle.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("duzenle.BackgroundImage")));
            this.duzenle.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.duzenle.ButtonText = "";
            this.duzenle.ButtonTextMarginLeft = 0;
            this.duzenle.ColorContrastOnClick = 45;
            this.duzenle.ColorContrastOnHover = 45;
            this.duzenle.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.duzenle.CustomizableEdges = borderEdges5;
            this.duzenle.DialogResult = System.Windows.Forms.DialogResult.None;
            this.duzenle.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.duzenle.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.duzenle.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.duzenle.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.duzenle.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.duzenle.ForeColor = System.Drawing.Color.White;
            this.duzenle.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.duzenle.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.duzenle.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.duzenle.IconMarginLeft = 11;
            this.duzenle.IconPadding = 5;
            this.duzenle.IconRightAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.duzenle.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.duzenle.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.duzenle.IconSize = 25;
            this.duzenle.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.duzenle.IdleBorderRadius = 25;
            this.duzenle.IdleBorderThickness = 2;
            this.duzenle.IdleFillColor = System.Drawing.Color.White;
            this.duzenle.IdleIconLeftImage = global::b201210009.Properties.Resources.duzenle1;
            this.duzenle.IdleIconRightImage = null;
            this.duzenle.IndicateFocus = false;
            this.duzenle.Location = new System.Drawing.Point(777, 28);
            this.duzenle.Margin = new System.Windows.Forms.Padding(2);
            this.duzenle.Name = "duzenle";
            this.duzenle.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.duzenle.OnDisabledState.BorderRadius = 25;
            this.duzenle.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.duzenle.OnDisabledState.BorderThickness = 2;
            this.duzenle.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.duzenle.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.duzenle.OnDisabledState.IconLeftImage = null;
            this.duzenle.OnDisabledState.IconRightImage = null;
            this.duzenle.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.duzenle.onHoverState.BorderRadius = 25;
            this.duzenle.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.duzenle.onHoverState.BorderThickness = 2;
            this.duzenle.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.duzenle.onHoverState.ForeColor = System.Drawing.Color.White;
            this.duzenle.onHoverState.IconLeftImage = global::b201210009.Properties.Resources.duzenleBeyaz;
            this.duzenle.onHoverState.IconRightImage = null;
            this.duzenle.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.duzenle.OnIdleState.BorderRadius = 25;
            this.duzenle.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.duzenle.OnIdleState.BorderThickness = 2;
            this.duzenle.OnIdleState.FillColor = System.Drawing.Color.White;
            this.duzenle.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.duzenle.OnIdleState.IconLeftImage = global::b201210009.Properties.Resources.duzenle1;
            this.duzenle.OnIdleState.IconRightImage = null;
            this.duzenle.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.duzenle.OnPressedState.BorderRadius = 25;
            this.duzenle.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.duzenle.OnPressedState.BorderThickness = 2;
            this.duzenle.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.duzenle.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.duzenle.OnPressedState.IconLeftImage = global::b201210009.Properties.Resources.duzenleBeyaz;
            this.duzenle.OnPressedState.IconRightImage = null;
            this.duzenle.Size = new System.Drawing.Size(35, 35);
            this.duzenle.TabIndex = 16;
            this.duzenle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.duzenle.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.duzenle.TextMarginLeft = 0;
            this.duzenle.TextPadding = new System.Windows.Forms.Padding(0);
            this.duzenle.UseDefaultRadiusAndThickness = true;
            // 
            // bunifuDataGridView1
            // 
            this.bunifuDataGridView1.AllowCustomTheming = false;
            this.bunifuDataGridView1.AllowUserToResizeRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(203)))), ((int)(((byte)(211)))), ((int)(((byte)(211)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.bunifuDataGridView1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuDataGridView1.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bunifuDataGridView1.AutoSizeRowsMode = System.Windows.Forms.DataGridViewAutoSizeRowsMode.DisplayedCells;
            this.bunifuDataGridView1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(219)))), ((int)(((byte)(219)))));
            this.bunifuDataGridView1.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bunifuDataGridView1.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bunifuDataGridView1.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DarkSlateGray;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(63)))), ((int)(((byte)(63)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bunifuDataGridView1.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.bunifuDataGridView1.ColumnHeadersHeight = 40;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(203)))), ((int)(((byte)(211)))), ((int)(((byte)(211)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(130)))), ((int)(((byte)(149)))), ((int)(((byte)(149)))));
            this.bunifuDataGridView1.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.BackColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuDataGridView1.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(202)))), ((int)(((byte)(202)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(37)))), ((int)(((byte)(63)))), ((int)(((byte)(63)))));
            this.bunifuDataGridView1.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.CurrentTheme.Name = null;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(219)))), ((int)(((byte)(219)))));
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(130)))), ((int)(((byte)(149)))), ((int)(((byte)(149)))));
            this.bunifuDataGridView1.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(213)))), ((int)(((byte)(219)))), ((int)(((byte)(219)))));
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(130)))), ((int)(((byte)(149)))), ((int)(((byte)(149)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bunifuDataGridView1.DefaultCellStyle = dataGridViewCellStyle3;
            this.bunifuDataGridView1.EnableHeadersVisualStyles = false;
            this.bunifuDataGridView1.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(192)))), ((int)(((byte)(202)))), ((int)(((byte)(202)))));
            this.bunifuDataGridView1.HeaderBackColor = System.Drawing.Color.DarkSlateGray;
            this.bunifuDataGridView1.HeaderBgColor = System.Drawing.Color.Empty;
            this.bunifuDataGridView1.HeaderForeColor = System.Drawing.Color.White;
            this.bunifuDataGridView1.Location = new System.Drawing.Point(20, 95);
            this.bunifuDataGridView1.Margin = new System.Windows.Forms.Padding(20);
            this.bunifuDataGridView1.MultiSelect = false;
            this.bunifuDataGridView1.Name = "bunifuDataGridView1";
            this.bunifuDataGridView1.ReadOnly = true;
            this.bunifuDataGridView1.RowHeadersVisible = false;
            dataGridViewCellStyle4.Padding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.bunifuDataGridView1.RowsDefaultCellStyle = dataGridViewCellStyle4;
            this.bunifuDataGridView1.RowTemplate.Height = 40;
            this.bunifuDataGridView1.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bunifuDataGridView1.Size = new System.Drawing.Size(841, 412);
            this.bunifuDataGridView1.TabIndex = 13;
            this.bunifuDataGridView1.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.DarkSlateGray;
            // 
            // ekle
            // 
            this.ekle.AllowAnimations = true;
            this.ekle.AllowMouseEffects = true;
            this.ekle.AllowToggling = false;
            this.ekle.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.ekle.AnimationSpeed = 200;
            this.ekle.AutoGenerateColors = false;
            this.ekle.AutoRoundBorders = false;
            this.ekle.AutoSizeLeftIcon = true;
            this.ekle.AutoSizeRightIcon = true;
            this.ekle.BackColor = System.Drawing.Color.Transparent;
            this.ekle.BackColor1 = System.Drawing.Color.White;
            this.ekle.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("ekle.BackgroundImage")));
            this.ekle.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.ekle.ButtonText = "";
            this.ekle.ButtonTextMarginLeft = 0;
            this.ekle.ColorContrastOnClick = 45;
            this.ekle.ColorContrastOnHover = 45;
            this.ekle.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.ekle.CustomizableEdges = borderEdges6;
            this.ekle.DialogResult = System.Windows.Forms.DialogResult.None;
            this.ekle.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ekle.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ekle.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ekle.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.ekle.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.ekle.ForeColor = System.Drawing.Color.White;
            this.ekle.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.ekle.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.ekle.IconLeftPadding = new System.Windows.Forms.Padding(4, 3, 3, 3);
            this.ekle.IconMarginLeft = 11;
            this.ekle.IconPadding = 5;
            this.ekle.IconRightAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ekle.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.ekle.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.ekle.IconSize = 25;
            this.ekle.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.ekle.IdleBorderRadius = 25;
            this.ekle.IdleBorderThickness = 2;
            this.ekle.IdleFillColor = System.Drawing.Color.White;
            this.ekle.IdleIconLeftImage = global::b201210009.Properties.Resources.ekle11;
            this.ekle.IdleIconRightImage = null;
            this.ekle.IndicateFocus = false;
            this.ekle.Location = new System.Drawing.Point(738, 28);
            this.ekle.Margin = new System.Windows.Forms.Padding(2);
            this.ekle.Name = "ekle";
            this.ekle.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.ekle.OnDisabledState.BorderRadius = 25;
            this.ekle.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.ekle.OnDisabledState.BorderThickness = 2;
            this.ekle.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.ekle.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.ekle.OnDisabledState.IconLeftImage = null;
            this.ekle.OnDisabledState.IconRightImage = null;
            this.ekle.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.ekle.onHoverState.BorderRadius = 25;
            this.ekle.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.ekle.onHoverState.BorderThickness = 2;
            this.ekle.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.ekle.onHoverState.ForeColor = System.Drawing.Color.White;
            this.ekle.onHoverState.IconLeftImage = global::b201210009.Properties.Resources.ekleBeyaz1;
            this.ekle.onHoverState.IconRightImage = null;
            this.ekle.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(39)))), ((int)(((byte)(137)))));
            this.ekle.OnIdleState.BorderRadius = 25;
            this.ekle.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.ekle.OnIdleState.BorderThickness = 2;
            this.ekle.OnIdleState.FillColor = System.Drawing.Color.White;
            this.ekle.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.ekle.OnIdleState.IconLeftImage = global::b201210009.Properties.Resources.ekle11;
            this.ekle.OnIdleState.IconRightImage = null;
            this.ekle.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ekle.OnPressedState.BorderRadius = 25;
            this.ekle.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.ekle.OnPressedState.BorderThickness = 2;
            this.ekle.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.ekle.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.ekle.OnPressedState.IconLeftImage = global::b201210009.Properties.Resources.ekleBeyaz1;
            this.ekle.OnPressedState.IconRightImage = null;
            this.ekle.Size = new System.Drawing.Size(35, 35);
            this.ekle.TabIndex = 17;
            this.ekle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.ekle.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.ekle.TextMarginLeft = 0;
            this.ekle.TextPadding = new System.Windows.Forms.Padding(0);
            this.ekle.UseDefaultRadiusAndThickness = true;
            // 
            // UsFatura
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.None;
            this.BackColor = System.Drawing.Color.White;
            this.Controls.Add(this.bunifuButton22);
            this.Controls.Add(this.bunifuButton21);
            this.Controls.Add(this.ara);
            this.Controls.Add(this.sil);
            this.Controls.Add(this.duzenle);
            this.Controls.Add(this.bunifuDataGridView1);
            this.Controls.Add(this.ekle);
            this.Font = new System.Drawing.Font("Arial", 9F);
            this.Name = "UsFatura";
            this.Size = new System.Drawing.Size(881, 534);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuDataGridView1)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton22;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 ara;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 sil;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 duzenle;
        private Bunifu.UI.WinForms.BunifuDataGridView bunifuDataGridView1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 ekle;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse2;
    }
}
